### PR TITLE
Export property_value_maximum_size

### PR DESCRIPTION
**Pull request by victormferrara**
Changes needed to export the metric about maximum threadpool size. I bumped the Hystrix version to the one that added this feature.

Please, let me know what you think and if you'll be able to make a release.

Thank you very much!

### CODE REVIEW

**Comment by ahus1** [comment]
Thanks, looks good to me. The checks ran fine on Travis CI; although I notice that I should probably move this repo to GitHub actions.

**Comment by ahus1** [comment]
The change is now included into 4.0.1-SNAPSHOT. 

Please see https://github.com/ahus1/prometheus-hystrix#development on how to use the snapshot repository. 

Please let me know if this snapshot works for you as you expect. I'll then publish a release to Maven central.

**Comment by victormferrara** [comment]
Yes, tested and works fine.

Thank you for the fast answer!

**Comment by ahus1** [comment]
I published version 4.1.0; it might take a while to promote to maven central. 

For everyone else looking for the full metric name: `hystrix_thread_pool_property_value_maximum_size`

**Pull request merged**
